name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: "pip"

      - name: Install Ruff
        run: pip3 install ruff

      - name: Install dependencies
        run: |
          pip3 install -r requirements-dev.lock

      # - name: Type-check with Pyright
      #   run: pyright .

      - name: Lint
        run: ruff check --output-format=github

      - name: Format
        run: ruff format --check 
